[tool.poetry]
name = "ailitekit"
version = "6.1.10"
description = "All popular Framework HF integration kit"
authors = ["Kammari Santhosh"]
readme = "README.md"
license = "MIT License"
repository = "https://github.com/santhosh/"
keywords = [""]
packages = [
    {include = "ailite"}
]
include = [
    "chat_gui.py",
    "chat_run.py"
]

[tool.poetry.dependencies]
ailitellm="0.1.6"
python = "^3.10"
dspy="^2.5.41"
langchain_core="0.3.24"



#[tool.poetry.scripts]
#claude-chat = "chat_gui:run_app"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"